# Use this to spin up a prometheus container for debugging

global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "spring"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:8080" # or port 8081 for CQRS app
